### ISSUE TITLE
hpcviewer crash while closing

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpcviewer#40]
I think the reason of the crash is because we close the application without opening the flat view. Hence, when it closes the cct tab, Eclipse "activates" the flat view and then try to create the tree.

```
!SESSION 2019-03-16 23:11:29.443 -----------------------------------------------                    
eclipse.buildId=unknown                                                                             
java.version=1.8.0_65                                                                               
java.vendor=Oracle Corporation                                                                      
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US                                       
Framework arguments:  hpctoolkit-lulesh2.0-database/                                                
Command-line arguments:  -os linux -ws gtk -arch x86_64 -consoleLog -data /home/la5/.hpctoolkit/hpcviewer hpctoolkit-lulesh2.0-database/

!ENTRY org.eclipse.ui.workbench 4 2 2019-03-16 23:12:32.588
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".
!STACK 0                                                                               
java.lang.NullPointerException                                                         
        at edu.rice.cs.hpc.data.experiment.scope.visitors.FlatViewScopeVisitor.getFlatCounterPart(FlatViewScopeVisitor.java:374)
        at edu.rice.cs.hpc.data.experiment.scope.visitors.FlatViewScopeVisitor.add(FlatViewScopeVisitor.java:110)               
        at edu.rice.cs.hpc.data.experiment.scope.visitors.FlatViewScopeVisitor.visit(FlatViewScopeVisitor.java:75)              
        at edu.rice.cs.hpc.data.experiment.scope.CallSiteScope.accept(CallSiteScope.java:89)                                    
        at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:761)                                        
        at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:766)                                        
        at edu.rice.cs.hpc.data.experiment.scope.Scope.dfsVisitScopeTree(Scope.java:766)                                        
        at edu.rice.cs.hpc.data.experiment.Experiment.createFlatView(Experiment.java:174)                                       
        at edu.rice.cs.hpc.viewer.scope.flat.FlatScopeView.createTree(FlatScopeView.java:59)                                    
        at edu.rice.cs.hpc.viewer.scope.DynamicScopeView.refreshTree(DynamicScopeView.java:62)                                  
        at edu.rice.cs.hpc.viewer.scope.DynamicScopeView$PartListener.partVisible(DynamicScopeView.java:125)                    
        at org.eclipse.ui.internal.PartListenerList2$7.run(PartListenerList2.java:172)                                          
        at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)                                                          
        at org.eclipse.core.runtime.Platform.run(Platform.java:888)                                                             
        at org.eclipse.ui.internal.PartListenerList2.fireEvent(PartListenerList2.java:55)                                       
        at org.eclipse.ui.internal.PartListenerList2.firePartVisible(PartListenerList2.java:170)                                
        at org.eclipse.ui.internal.PartService.firePartVisible(PartService.java:253)                                            
        at org.eclipse.ui.internal.PartService$PartVisible.fire(PartService.java:110)                                           
        at org.eclipse.ui.internal.PartService.processPartJobs(PartService.java:161)                                            
        at org.eclipse.ui.internal.PartService$PartListener.handleEvent(PartService.java:88)                                    
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)                                                     
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)                                                           
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1282)                                                           
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1263)                                                           
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:911)                                                          
        at org.eclipse.swt.widgets.Composite.setBounds(Composite.java:1358)                                                     
        at org.eclipse.swt.widgets.Control.setBounds(Control.java:737)                                                          
        at org.eclipse.ui.internal.LayoutPart.setBounds(LayoutPart.java:300)                                                    
        at org.eclipse.ui.internal.presentations.PresentablePart.setBounds(PresentablePart.java:170)                            
        at org.eclipse.ui.internal.presentations.util.PresentablePartFolder.layoutContent(PresentablePartFolder.java:131)       
        at org.eclipse.ui.internal.presentations.util.PresentablePartFolder.layout(PresentablePartFolder.java:412)              
        at org.eclipse.ui.internal.presentations.util.PresentablePartFolder.select(PresentablePartFolder.java:292)              
        at org.eclipse.ui.internal.presentations.util.LeftToRightTabOrder.select(LeftToRightTabOrder.java:65)                   
        at org.eclipse.ui.internal.presentations.util.TabbedStackPresentation.selectPart(TabbedStackPresentation.java:473)      
        at org.eclipse.ui.internal.PartStack.refreshPresentationSelection(PartStack.java:1245)                                  
        at org.eclipse.ui.internal.PartStack.setSelection(PartStack.java:1198)                                                  
        at org.eclipse.ui.internal.PartStack.updateContainerVisibleTab(PartStack.java:1648)                                     
        at org.eclipse.ui.internal.PartStack.remove(PartStack.java:866)
        at org.eclipse.ui.internal.PartStack.replace(PartStack.java:911)
        at org.eclipse.ui.internal.PerspectiveHelper.removePart(PerspectiveHelper.java:1254)
        at org.eclipse.ui.internal.Perspective.hideView(Perspective.java:602)
        at org.eclipse.ui.internal.WorkbenchPage.hideView(WorkbenchPage.java:2469)
        at edu.rice.cs.hpc.viewer.framework.ApplicationWorkbenchWindowAdvisor.removeViews(ApplicationWorkbenchWindowAdvisor.java:218)
```

**Comment by laksono** [comment]
cannot reproduce with the current version
