### ISSUE TITLE
hpcviewer crashes when sorting huge tree in bottom-up view

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpcviewer#45]
Platform: Linux
Database: Laghos gpu version

To reproduce:
- Open Laghos database
- Go to bottom-up view
- Sort an inclusive metric
- click a hot path
- Sort an exclusive metric

It should crash the application:
```
!ENTRY org.eclipse.ui 4 0 2019-05-20 12:02:20.141                    
!MESSAGE Unhandled event loop exception                              
!STACK 0                                                             
org.eclipse.swt.SWTException: Widget is disposed                     
        at org.eclipse.swt.SWT.error(SWT.java:4533)                  
        at org.eclipse.swt.SWT.error(SWT.java:4448)                  
        at org.eclipse.swt.SWT.error(SWT.java:4419)                  
        at org.eclipse.swt.widgets.Widget.error(Widget.java:483)     
        at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:420)
        at org.eclipse.swt.widgets.TreeItem.setItemCount(TreeItem.java:1630)
        at org.eclipse.jface.viewers.TreeViewer.lambda$2(TreeViewer.java:383)
        at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:349)
        at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1419)
        at org.eclipse.jface.viewers.TreeViewer.setChildCount(TreeViewer.java:375)                   
        at edu.rice.cs.hpc.viewer.scope.AbstractContentProvider.updateChildCount(AbstractContentProvider.java:71)
        at edu.rice.cs.hpc.viewer.scope.AbstractContentProvider.updateElement(AbstractContentProvider.java:61)   
        at org.eclipse.jface.viewers.TreeViewer.virtualLazyUpdateWidget(TreeViewer.java:985)                     
        at org.eclipse.jface.viewers.TreeViewer.virtualRefreshExpandedItems(TreeViewer.java:691)
        at org.eclipse.jface.viewers.TreeViewer.virtualRefreshExpandedItems(TreeViewer.java:699)
        at org.eclipse.jface.viewers.TreeViewer.virtualRefreshExpandedItems(TreeViewer.java:699)
        at org.eclipse.jface.viewers.TreeViewer.virtualRefreshExpandedItems(TreeViewer.java:699)
        at org.eclipse.jface.viewers.TreeViewer.virtualRefreshExpandedItems(TreeViewer.java:699)
        at org.eclipse.jface.viewers.TreeViewer.virtualRefreshExpandedItems(TreeViewer.java:699)
        at org.eclipse.jface.viewers.TreeViewer.virtualRefreshExpandedItems(TreeViewer.java:699)
        at org.eclipse.jface.viewers.TreeViewer.virtualRefreshExpandedItems(TreeViewer.java:699)
        at org.eclipse.jface.viewers.TreeViewer.virtualRefreshExpandedItems(TreeViewer.java:699)
        at org.eclipse.jface.viewers.TreeViewer.virtualRefreshExpandedItems(TreeViewer.java:699)
        at org.eclipse.jface.viewers.TreeViewer.virtualRefreshExpandedItems(TreeViewer.java:699)
        at org.eclipse.jface.viewers.TreeViewer.internalRefreshStruct(TreeViewer.java:666)
        at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1888)
        at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1845)
        at org.eclipse.jface.viewers.AbstractTreeViewer.internalRefresh(AbstractTreeViewer.java:1831)
        at org.eclipse.jface.viewers.StructuredViewer.lambda$0(StructuredViewer.java:1519)
        at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1458)
        at org.eclipse.jface.viewers.TreeViewer.preservingSelection(TreeViewer.java:354)
        at org.eclipse.jface.viewers.StructuredViewer.preservingSelection(StructuredViewer.java:1419)
        at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1519)
        at org.eclipse.jface.viewers.ColumnViewer.refresh(ColumnViewer.java:523)
        at org.eclipse.jface.viewers.StructuredViewer.refresh(StructuredViewer.java:1478)
        at edu.rice.cs.hpc.viewer.scope.AbstractContentProvider.sort_column(AbstractContentProvider.java:87)
        at edu.rice.cs.hpc.viewer.scope.ScopeSelectionAdapter.setSorter(ScopeSelectionAdapter.java:103)
        at edu.rice.cs.hpc.viewer.scope.ScopeSelectionAdapter.widgetSelected(ScopeSelectionAdapter.java:63)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
```

**Comment by laksono** [comment]
@jmellorcrummey: Just to let you know, hpcviewer crashes when sorting Laghos database in bottom-up view.

**Comment by laksono** [comment]
Not reproducible on Eclipse Neon
