### ISSUE TITLE
hpctraceviewer java errors

### ISSUE THREAD

**Issue by jmellorcrummey** [HPCToolkit/hpcviewer#55]
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
java.lang.NullPointerException
        at org.eclipse.swt.graphics.GC.drawImage(GC.java:945)
        at org.eclipse.swt.graphics.GC.drawImage(GC.java:908)
        at edu.rice.cs.hpc.traceviewer.depth.DepthViewPaint.drawPainting(DepthViewPaint.java:97)
        at edu.rice.cs.hpc.traceviewer.painter.BaseViewPaint.endPainting(BaseViewPaint.java:322)
        at edu.rice.cs.hpc.traceviewer.painter.BaseViewPaint.executePaint(BaseViewPaint.java:257)
        at edu.rice.cs.hpc.traceviewer.painter.BaseViewPaint.paint(BaseViewPaint.java:207)
        at edu.rice.cs.hpc.traceviewer.painter.BaseViewPaint.run(BaseViewPaint.java:89)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by laksono** [comment]
The cause of the problem is due to data race accessing `masterGC` that has been disposed:
```
 94   if (masterGC != null && !masterGC.isDisposed() && img != null && img.image != null)
 95   {
 96      try {
 97        masterGC.drawImage(img.image, 0, 0, img.image.getBounds().width,
 98           img.image.getBounds().height, 0,
 99           Math.round(img.position*numPixels),
100           img.image.getBounds().width, img.image.getBounds().height);
101        } catch (Exception e) {
102           e.printStackTrace();
103        }
104     img.image.dispose();
105   }
```
But since we have fixed job scheduling and only allow one job at a time, this bug should be fixed. See a75e9691334299a012fb3b1d8cd674b76106b332 and af5477e7c424c1e9b5f7562fd713f68a2087375e
