### ISSUE TITLE
Crash while exiting hpctraceviewer

### ISSUE THREAD

**Issue by laksono** [HPCToolkit/hpcviewer#89]
Possible cause:
```
	at org.eclipse.swt.widgets.Widget.removeListener(Widget.java:1140)
	at org.eclipse.jface.window.ToolTip.deactivate(ToolTip.java:201)
	at org.eclipse.jface.window.ToolTip$1.widgetDisposed(ToolTip.java:109)
```
The complete error message while closing hpctraceviewer:
```
Max memory  : 2144 MB
java version: 1.7.0_75
!SESSION 2020-06-08 13:06:06.662 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_75
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product edu.rice.cs.hpc.traceviewer.product -clearPersistedState
Command-line arguments:  -product edu.rice.cs.hpc.traceviewer.product -data /home/la5/workspace/indigo/hpctoolkit/hpcviewer/../runtime-hpctraceviewer.indigo.product -dev file:/home/la5/workspace/indigo/hpctoolkit/hpcviewer/.metadata/.plugins/org.eclipse.pde.core/hpctraceviewer.indigo.product/dev.properties -os linux -ws gtk -arch x86_64 -consoleLog -clearPersistedState

!ENTRY org.eclipse.ui 4 0 2020-06-08 13:07:11.784
!MESSAGE Widget is disposed
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4282)
	at org.eclipse.swt.SWT.error(SWT.java:4197)
	at org.eclipse.swt.SWT.error(SWT.java:4168)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:466)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:403)
	at org.eclipse.swt.widgets.Widget.removeListener(Widget.java:1140)
	at org.eclipse.jface.window.ToolTip.deactivate(ToolTip.java:201)
	at org.eclipse.jface.window.ToolTip$1.widgetDisposed(ToolTip.java:109)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1282)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1263)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1080)
	at org.eclipse.swt.widgets.Control.release(Control.java:3488)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:1294)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1083)
	at org.eclipse.swt.widgets.Control.release(Control.java:3488)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:1294)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1083)
	at org.eclipse.swt.widgets.Control.release(Control.java:3488)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:1294)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1083)
	at org.eclipse.swt.widgets.Control.release(Control.java:3488)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:462)
	at org.eclipse.ui.internal.PartPane.dispose(PartPane.java:180)
	at org.eclipse.ui.internal.ViewPane.dispose(ViewPane.java:204)
	at org.eclipse.ui.internal.WorkbenchPartReference.dispose(WorkbenchPartReference.java:681)
	at org.eclipse.ui.internal.WorkbenchPage.disposePart(WorkbenchPage.java:1797)
	at org.eclipse.ui.internal.WorkbenchPage.partRemoved(WorkbenchPage.java:1789)
	at org.eclipse.ui.internal.ViewFactory.releaseView(ViewFactory.java:257)
	at org.eclipse.ui.internal.Perspective.dispose(Perspective.java:292)
	at org.eclipse.ui.internal.WorkbenchPage.dispose(WorkbenchPage.java:1868)
	at org.eclipse.ui.internal.WorkbenchWindow.closeAllPages(WorkbenchWindow.java:894)
	at org.eclipse.ui.internal.WorkbenchWindow.hardClose(WorkbenchWindow.java:1729)
	at org.eclipse.ui.internal.WorkbenchWindow.busyClose(WorkbenchWindow.java:730)
	at org.eclipse.ui.internal.WorkbenchWindow.access$0(WorkbenchWindow.java:715)
	at org.eclipse.ui.internal.WorkbenchWindow$6.run(WorkbenchWindow.java:867)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:865)
	at org.eclipse.jface.window.WindowManager.close(WindowManager.java:109)
	at org.eclipse.ui.internal.Workbench$18.run(Workbench.java:1114)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.Workbench.busyClose(Workbench.java:1111)
	at org.eclipse.ui.internal.Workbench.access$15(Workbench.java:1040)
	at org.eclipse.ui.internal.Workbench$25.run(Workbench.java:1284)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1282)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1254)
	at org.eclipse.ui.internal.WorkbenchWindow.busyClose(WorkbenchWindow.java:727)
	at org.eclipse.ui.internal.WorkbenchWindow.access$0(WorkbenchWindow.java:715)
	at org.eclipse.ui.internal.WorkbenchWindow$6.run(WorkbenchWindow.java:867)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:865)
	at org.eclipse.jface.window.Window.handleShellCloseEvent(Window.java:741)
	at org.eclipse.jface.window.Window$3.shellClosed(Window.java:687)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:98)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1282)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1267)
	at org.eclipse.swt.widgets.Shell.closeWidget(Shell.java:617)
	at org.eclipse.swt.widgets.Shell.gtk_delete_event(Shell.java:1189)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1735)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:5016)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4408)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:8422)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1245)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2276)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3207)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at edu.rice.cs.hpc.traceviewer.framework.Application.start(Application.java:26)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1386)

!ENTRY org.eclipse.ui 4 0 2020-06-08 13:07:11.803
!MESSAGE Widget is disposed
!STACK 0
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4282)
	at org.eclipse.swt.SWT.error(SWT.java:4197)
	at org.eclipse.swt.SWT.error(SWT.java:4168)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:466)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:403)
	at org.eclipse.swt.widgets.Widget.removeListener(Widget.java:1140)
	at org.eclipse.jface.window.ToolTip.deactivate(ToolTip.java:201)
	at org.eclipse.jface.window.ToolTip$1.widgetDisposed(ToolTip.java:109)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:123)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1282)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1263)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1080)
	at org.eclipse.swt.widgets.Control.release(Control.java:3488)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:1294)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1083)
	at org.eclipse.swt.widgets.Control.release(Control.java:3488)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:1294)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1083)
	at org.eclipse.swt.widgets.Control.release(Control.java:3488)
	at org.eclipse.swt.widgets.Composite.releaseChildren(Composite.java:1294)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1083)
	at org.eclipse.swt.widgets.Control.release(Control.java:3488)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:462)
	at org.eclipse.ui.internal.PartPane.dispose(PartPane.java:180)
	at org.eclipse.ui.internal.ViewPane.dispose(ViewPane.java:204)
	at org.eclipse.ui.internal.WorkbenchPartReference.dispose(WorkbenchPartReference.java:681)
	at org.eclipse.ui.internal.WorkbenchPage.disposePart(WorkbenchPage.java:1797)
	at org.eclipse.ui.internal.WorkbenchPage.partRemoved(WorkbenchPage.java:1789)
	at org.eclipse.ui.internal.ViewFactory.releaseView(ViewFactory.java:257)
	at org.eclipse.ui.internal.Perspective.dispose(Perspective.java:292)
	at org.eclipse.ui.internal.WorkbenchPage.dispose(WorkbenchPage.java:1868)
	at org.eclipse.ui.internal.WorkbenchWindow.closeAllPages(WorkbenchWindow.java:894)
	at org.eclipse.ui.internal.WorkbenchWindow.hardClose(WorkbenchWindow.java:1729)
	at org.eclipse.ui.internal.WorkbenchWindow.busyClose(WorkbenchWindow.java:730)
	at org.eclipse.ui.internal.WorkbenchWindow.access$0(WorkbenchWindow.java:715)
	at org.eclipse.ui.internal.WorkbenchWindow$6.run(WorkbenchWindow.java:867)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:865)
	at org.eclipse.jface.window.WindowManager.close(WindowManager.java:109)
	at org.eclipse.ui.internal.Workbench$18.run(Workbench.java:1114)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.Workbench.busyClose(Workbench.java:1111)
	at org.eclipse.ui.internal.Workbench.access$15(Workbench.java:1040)
	at org.eclipse.ui.internal.Workbench$25.run(Workbench.java:1284)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1282)
	at org.eclipse.ui.internal.Workbench.close(Workbench.java:1254)
	at org.eclipse.ui.internal.WorkbenchWindow.busyClose(WorkbenchWindow.java:727)
	at org.eclipse.ui.internal.WorkbenchWindow.access$0(WorkbenchWindow.java:715)
	at org.eclipse.ui.internal.WorkbenchWindow$6.run(WorkbenchWindow.java:867)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.internal.WorkbenchWindow.close(WorkbenchWindow.java:865)
	at org.eclipse.jface.window.Window.handleShellCloseEvent(Window.java:741)
	at org.eclipse.jface.window.Window$3.shellClosed(Window.java:687)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:98)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1258)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1282)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1267)
	at org.eclipse.swt.widgets.Shell.closeWidget(Shell.java:617)
	at org.eclipse.swt.widgets.Shell.gtk_delete_event(Shell.java:1189)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1735)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:5016)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4408)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:8422)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1245)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2276)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3207)
	at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
	at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
	at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
	at edu.rice.cs.hpc.traceviewer.framework.Application.start(Application.java:26)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1386)

```

**Comment by jmellorcrummey** [comment]
Can we just catch these errors in Java and discard them without emitting anything if we are closing?

**Comment by jmellorcrummey** [comment]
By the way, I see these errors being reported to the terminal. We are piping stderr into a log. Do they get sent to stdout?

**Comment by laksono** [comment]
The error should be printed to stderr. I think this happened while running hpcviewer on Eclipse. It happens rarely, but it does happen.

Btw, the main problem is Eclipse/SWT removes a listener **after** the widget is freed. This shouldn't happen. 

Is this an Eclipse bug? Or did I configure it incorrectly? It requires further investigation.

**Comment by jmellorcrummey** [comment]
for me, it is repeatable. every time at sandia on x86. despite the fact that the hpctraceviewer script redirects stderr to a log, this prints at the terminal. i don’t onow why.

**Comment by laksono** [comment]
It does happen on gpu.cs too. I can reproduce it easily. Strange.

**Comment by laksono** [comment]
Tested on gpu.cs: there is no problem with release 2020.04. Only 2020.05 has this issue.

**Comment by laksono** [comment]
I can confirm that it doesn't occur with the latest repo or release: http://hpctoolkit.org/download/hpcviewer/2020.06/
I tested on llnl.cs and gpu.cs. Not tested on national labs yet.
